// Auto-generated by recorder.py
// Last updated: 2026-06-24 18:01:57
window.__RECORDING_DATA__ = [
  {
    "date": "2026-06-23",
    "start_time": "19:10:18",
    "duration_min": 0,
    "file": "douyin_live_388670993636_20260623_191018.mp4",
    "file_size_mb": 4.1,
    "room_id": "388670993636",
    "stream_url": ""
  },
  {
    "date": "2026-06-23",
    "start_time": "19:19:39",
    "duration_min": 0,
    "file": "douyin_live_388670993636_20260623_191939.mp4",
    "file_size_mb": 1492.8,
    "room_id": "388670993636",
    "stream_url": ""
  }
];
